name: manimator
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy>=1.24.0
  - scipy>=1.10.0
  - libstdcxx-ng  #espeak problem bruh
  - pip:
      - streamlit>=1.27.0
      - manim>=0.17.3
      - kokoro>=0.3.1
      - soundfile
      - google-genai
      - python-dotenv
      - transformers
      - accelerate
      - httpx>=0.24.0
  - pytorch
  - torchvision
  - torchaudio
  - google-genai
